# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Ust <- function(b, eta) {
    .Call('_bestPLS_Ust', PACKAGE = 'bestPLS', b, eta)
}

case_1 <- function(M, c, eps, maxstep, eta) {
    .Call('_bestPLS_case_1', PACKAGE = 'bestPLS', M, c, eps, maxstep, eta)
}
